name: .NET

env:
  GITHUB_USER: TA-RPA
  GITHUB_FEED: https://nuget.pkg.github.com/TA-RPA
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity minimal

      - name: Package
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: dotnet pack -c Release --no-restore --no-build --version-suffix "github"
      - uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: nuget/*